.TH C-SIMPLE SHELL 1 simple_shell\-0.1
.SH NAME
C-SIMPLE SHELL - A simple shell program
.SH LIBRARY
Standard C library
.SH SYNOPSIS
C-SIMPLE SHELL
#include <"shell.h">
.P
int display_prompt(void);
.SH DESCRIPTION
C-SIMPLE SHELL
- is a basic command-line interpreter that allows users to interact with the operating system by entering commands
.SH RETURN VALUE
It executes the corresponding program or operation that you give the command line in your operator
.SH AUTHOR(S)
This code was mostly written in collaboration by
.I Xavier J. Cruz Santiago
.B &
.I Angel Velazquez
.R for a project called C-SIMPLE SHELL
.SH Bugs
If encountering any issues, I recommend making your own program instead. Do some research. Do some more research. Maybe ask some peers. Or call Xavier.
.SH COPYRIGHT
Copyright \(co 2024 [
.I HOLBERTON C SCHOOL
.R ]
.SH NOTES
.B  This man page was completed for proper documentation of a function. It was created as part of a project for Holberton School. It is not intended for practical use.
